
project_id = "cylrmgrxawqdrwrqvenw"
name = "app"

[api]
node_version = "18"
enabled_apis = ["rest", "graphql", "realtime"]
port = 54321

[api.headers]
x-default = "some value"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true
log_level = "INFO"
webhook_event_cb = "supabase_functions.relay_realtime_websocket_events"

[studio]
port = 54323
api_url = "http://localhost"

[inbucket]
port = 54324

[auth]
port = 54325
uri = "http://localhost:54321/auth/v1"
enable_pwd_confirmation = false
enable_auto_pwd_recovery = false
enable_auto_pwd_reset = false
enable_pwd_strength = false
email_templates_base_path = "/var/lib/supabase/storage/templates"

[functions]
port = 54326
function_timeout_seconds = 30

[functions.send-contact-email]
verify_jwt = false

[storage]
port = 54327
file_size_limit = 52428800
