// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://melyxtihhwjsszoiumik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lbHl4dGloaHdqc3N6b2l1bWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NjI4ODYsImV4cCI6MjA2MjMzODg4Nn0.yaXUXTMN6LFcV-RSYX7KxRU-4QGTwZDmjdo6LcCzgAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);